version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  frontend-service:
    image: frontend
    restart: always
    ports:
      - 9093:9090
    environment:
      HTTP_PORT: 9090
      SERVICE_AIRPORTS: http://airport-service:9090
      SERVICE_COUNTRIES: http://country-service:9090
      SERVICE_RUNWAYS: http://runway-service:9090
      SERVICE_RUNWAYSCOUNTRY: http://runways-country-service:9090

  runways-country-service:
    image: runways-country
    restart: always
    ports:
      - 9094:9090
    environment:
      HTTP_PORT: 9090
      SERVICE_AIRPORTS: http://airport-service:9090
      SERVICE_RUNWAYS: http://runway-service:9090

  runway-service:
    image: runways
    restart: always
    ports:
      - 9092:9090
    environment:
      HTTP_PORT: 9090
      MONGO_DOMAIN: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_COLLECTION: runways
      MONGO_DB: runways

  airport-service:
    image: airports
    restart: always
    ports:
      - 9091:9090
    environment:
      HTTP_PORT: 9090
      MONGO_DOMAIN: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_COLLECTION: airports
      MONGO_DB: airports

  country-service:
    image: countries
    restart: always
    ports:
      - 9090:9090
    environment:
      HTTP_PORT: 9090
      MONGO_DOMAIN: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_COLLECTION: countries
      MONGO_DB: countries

  mongo-seed-airports:
    image: mongo-seed
    links:
      - mongo
    volumes:
      -  ${PWD}/data/json/airports.json:/app/data.json
    environment:
      MONGO_DOMAIN: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_COLLECTION: airports
      MONGO_DB: airports

  mongo-seed-countries:
    image: mongo-seed
    links:
      - mongo
    volumes:
      - ${PWD}/data/json/countries.json:/app/data.json
    environment:
      MONGO_DOMAIN: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_COLLECTION: countries
      MONGO_DB: countries

  mongo-seed-runways:
    image: mongo-seed
    links:
      - mongo
    volumes:
      - ${PWD}/data/json/runways.json:/app/data.json
    environment:
      MONGO_DOMAIN: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_COLLECTION: runways
      MONGO_DB: runways

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example