apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-config
  namespace: kube-system
type: Opaque
data:
  config: dmVyc2lvbjogMC4xCmxvZzoKICBmaWVsZHM6CiAgICBzZXJ2aWNlOiByZWdpc3RyeQpzdG9yYWdlOgogIGNhY2hlOgogICAgYmxvYmRlc2NyaXB0b3I6IGlubWVtb3J5CiAgZmlsZXN5c3RlbToKICAgIHJvb3RkaXJlY3Rvcnk6IC92YXIvbGliL3JlZ2lzdHJ5CiAgZGVsZXRlOgogICAgZW5hYmxlZDogdHJ1ZQpodHRwOgogIGFkZHI6IDo1MDAwCiAgaGVhZGVyczoKICAgIFgtQ29udGVudC1UeXBlLU9wdGlvbnM6IFtub3NuaWZmXQpoZWFsdGg6CiAgc3RvcmFnZWRyaXZlcjoKICAgIGVuYWJsZWQ6IHRydWUKICAgIGludGVydmFsOiAxMHMKICAgIHRocmVzaG9sZDogMw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
  labels:
    component: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      component: registry
  template:
    metadata:
      labels:
        component: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              name: persistent-volume
              subPath: registry/data
            - mountPath: /etc/docker/registry
              name: registry-config
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: registry-data
        - name: registry-config
          secret:
            secretName: registry-config
            items:
              - key: config
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: kube-system
spec:
  ports:
    -  port: 80
       protocol: TCP
       targetPort: 5000
  selector:
    component: registry
  type: ClusterIP
