apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world-cron
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo Hello world
          restartPolicy: OnFailure