apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: gcloud-cred
  namespace: jenkins
type: Opaque
data:
  access_token: ${GCLOUD_ACCESS_TOKEN}
  user_name: ${GCLOUD_USER_NAME}
  host_name: ${GCLOUD_HOSTNAME}
  project_name: ${GCLOUD_PROJECTNAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    component: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jenkins
  template:
    metadata:
      labels:
        component: jenkins
    spec:
      containers:
        - name: jenkins
          image: eu.gcr.io/michaelhaddon-223413/jenkins:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: GCLOUD_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gcloud-cred
                  key: access_token
            - name: GCLOUD_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: gcloud-cred
                  key: user_name
            - name: GCLOUD_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: gcloud-cred
                  key: host_name
            - name: GCLOUD_PROJECTNAME
              valueFrom:
                secretKeyRef:
                  name: gcloud-cred
                  key: project_name
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run
              name: docker-sock
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - cat
                - /var/jenkins_started
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - name: jenkins
      port: 80
      targetPort: 8080
    - name: jenkins-agent
      port: 50000
      targetPort: 50000
  selector:
    component: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
spec:
  backend:
    serviceName: jenkins-svc
    servicePort: 80