apiVersion: apps/v1
kind: Deployment
metadata:
  name: airports-db
  namespace: ${NAMESPACE}
  labels:
    component: airports-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airports-db
  template:
    metadata:
      labels:
        component: airports-db
        access-airports-db: "1"
    spec:
      containers:
        - name: airports-db
          image: mongo:4.1
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 64Mi
          ports:
            - containerPort: 27017
              name: transport
              protocol: TCP
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airports-db-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airports-db-credentials
                  key: password
            - name: MONGO_DOMAIN
              value: 'airports-db.${NAMESPACE}.svc.cluster.local'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_COLLECTION
              value: 'airports'
            - name: MONGO_DB
              value: 'airports'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: airports-db-svc
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 27017
       protocol: TCP
       targetPort: 27017
  selector:
    component: airports-db
  type: ClusterIP

