apiVersion: v1
kind: Secret
metadata:
  name: airports-db-credentials
type: Opaque
data:
  username: '${AIRPORTS_DB_USR_B64}'
  password: '${AIRPORTS_DB_PW_B64}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airports-db-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airports-db
  namespace: ${NAMESPACE}
  labels:
    component: airports-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airports-db
  template:
    metadata:
      labels:
        component: airports-db
    spec:
      containers:
        - name: airports-db
          image: mongo:4.1
          resources:
            limits:
              cpu: "0.8"
              memory: 512Mi
            requests:
              cpu: "0.2"
              memory: 128Mi
          ports:
            - containerPort: 27017
              name: transport
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airports-db-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airports-db-credentials
                  key: password
          volumeMounts:
            - mountPath: /data/db
              name: persistent-volume
              subPath: mongo/data
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /bin/echo "$(test="$(/usr/bin/mongo localhost:27017/test --quiet <<< 'db.runCommand("ping").ok')"; ((test ^= 1)); /bin/echo "${test}")"
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /bin/echo "$(test="$(/usr/bin/mongo localhost:27017/test --quiet <<< 'db.runCommand("ping").ok')"; ((test ^= 1)); /bin/echo "${test}")"
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: airports-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: airports-db-svc
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 27017
       protocol: TCP
       targetPort: 27017
  selector:
    component: airports-db
  type: ClusterIP

