apiVersion: apps/v1
kind: Deployment
metadata:
  name: airports
  namespace: ${NAMESPACE}
  labels:
    component: airports
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airports
  template:
    metadata:
      labels:
        component: airports
        access-airports-db: "1"
    spec:
      containers:
        - name: airports
          image: ${GCLOUD_HOSTNAME}/${GCLOUD_PROJECTNAME}/airports:${SERVICE_AIRPORTS_VER}
          resources:
            limits:
              cpu: "150m"
              memory: 256Mi
            requests:
              cpu: "50m"
              memory: 64Mi
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airports-db-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airports-db-credentials
                  key: password
            - name: MONGO_DOMAIN
              value: 'airports-db.${NAMESPACE}.svc.cluster.local'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_COLLECTION
              value: 'airports'
            - name: MONGO_DB
              value: 'airports'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: airports
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 80
       protocol: TCP
       targetPort: 8080
  selector:
    component: airports
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-airports
  namespace: ${NAMESPACE}
spec:
  podSelector:
    matchLabels:
      component: airports
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access-airports: "1"
          namespaceSelector:
            matchLabels:
              name: '${NAMESPACE}'
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-airports
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    kind: Deployment
    name: airports
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
