apiVersion: apps/v1
kind: Deployment
metadata:
  name: countries
  namespace: ${NAMESPACE}
  labels:
    component: countries
spec:
  replicas: 1
  selector:
    matchLabels:
      component: countries
  template:
    metadata:
      labels:
        component: countries
        access-countries-db: "1"
    spec:
      containers:
        - name: countries
          image: ${GCLOUD_HOSTNAME}/${GCLOUD_PROJECTNAME}/countries:${SERVICE_COUNTRIES_VER}
          resources:
            limits:
              cpu: "350m"
              memory: 256Mi
            requests:
              cpu: "200m"
              memory: 64Mi
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: countries-db-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: countries-db-credentials
                  key: password
            - name: MONGO_DOMAIN
              value: 'countries-db.${NAMESPACE}.svc.cluster.local'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_COLLECTION
              value: 'countries'
            - name: MONGO_DB
              value: 'countries'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: countries
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 80
       protocol: TCP
       targetPort: 8080
  selector:
    component: countries
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-countries
  namespace: ${NAMESPACE}
spec:
  podSelector:
    matchLabels:
      component: countries
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access-countries: "1"
        - namespaceSelector:
            matchLabels:
              name: '${NAMESPACE}'
