apiVersion: apps/v1
kind: Deployment
metadata:
  name: runways
  namespace: ${NAMESPACE}
  labels:
    component: runways
spec:
  replicas: 1
  selector:
    matchLabels:
      component: runways
  template:
    metadata:
      labels:
        component: runways
        access-runways-db: "1"
    spec:
      containers:
        - name: runways
          image: ${GCLOUD_HOSTNAME}/${GCLOUD_PROJECTNAME}/runways:${SERVICE_RUNWAYS_VER}
          resources:
            limits:
              cpu: "150m"
              memory: 256Mi
            requests:
              cpu: "100m"
              memory: 64Mi
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: runways-db-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: runways-db-credentials
                  key: password
            - name: MONGO_DOMAIN
              value: 'runways-db.${NAMESPACE}.svc.cluster.local'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_COLLECTION
              value: 'runways'
            - name: MONGO_DB
              value: 'runways'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: runways
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 80
       protocol: TCP
       targetPort: 8080
  selector:
    component: runways
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-runways
  namespace: ${NAMESPACE}
spec:
  podSelector:
    matchLabels:
      component: runways
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access-runways: "1"
          namespaceSelector:
            matchLabels:
              name: '${NAMESPACE}'
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-runways
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runways
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Pods
      pods:
        metricName: current_connections
        targetAverageValue: 3
