apiVersion: apps/v1
kind: Deployment
metadata:
  name: runways-country
  namespace: ${NAMESPACE}
  labels:
    component: runways-country
spec:
  replicas: 1
  selector:
    matchLabels:
      component: runways-country
  template:
    metadata:
      labels:
        component: runways-country
        access-airports: "1"
        access-runways: "1"
    spec:
      containers:
        - name: runways-country
          image: ${GCLOUD_HOSTNAME}/${GCLOUD_PROJECTNAME}/runways-country:${SERVICE_RUNWAYSCOUNTRY_VER}
          resources:
            limits:
              cpu: "350m"
              memory: 256Mi
            requests:
              cpu: "200m"
              memory: 64Mi
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_AIRPORTS
              value: 'http://airports.${NAMESPACE}.svc.cluster.local'
            - name: SERVICE_RUNWAYS
              value: 'http://runways.${NAMESPACE}.svc.cluster.local'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: runways-country
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 80
       protocol: TCP
       targetPort: 8080
  selector:
    component: runways-country
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-runways-country
  namespace: ${NAMESPACE}
spec:
  podSelector:
    matchLabels:
      component: runways-country
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access-runways-country: "1"
        - namespaceSelector:
            matchLabels:
              name: '${NAMESPACE}'
