apiVersion: v1
kind: Secret
metadata:
  name: runways-db-credentials
  namespace: ${NAMESPACE}
type: Opaque
data:
  username: '${RUNWAYS_DB_USR_B64}'
  password: '${RUNWAYS_DB_PW_B64}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runways-db-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runways-db
  namespace: ${NAMESPACE}
  labels:
    component: runways-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: runways-db
  template:
    metadata:
      labels:
        component: runways-db
    spec:
      containers:
        - name: runways-db
          image: mongo:${SERVICE_MONGO_VER}
          resources:
            limits:
              cpu: "250m"
              memory: 512Mi
            requests:
              cpu: "100m"
              memory: 128Mi
          ports:
            - containerPort: 27017
              name: transport
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: runways-db-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: runways-db-credentials
                  key: password
          volumeMounts:
            - mountPath: /data/db
              name: persistent-volume
              subPath: mongo/data
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /bin/echo "$(test="$(/usr/bin/mongo --authenticationDatabase admin --username "$MONGO_INITDB_ROOT_USERNAME" --password "$MONGO_INITDB_ROOT_PASSWORD" localhost:27017/test --quiet <<< 'db.runCommand("ping").ok')"; ((test ^= 1)); /bin/echo "${test}")"
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /bin/echo "$(test="$(/usr/bin/mongo --authenticationDatabase admin --username "$MONGO_INITDB_ROOT_USERNAME" --password "$MONGO_INITDB_ROOT_PASSWORD" localhost:27017/test --quiet <<< 'db.runCommand("ping").ok')"; ((test ^= 1)); /bin/echo "${test}")"
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: runways-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: runways-db
  namespace: ${NAMESPACE}
spec:
  ports:
    -  name: transport
       port: 27017
       protocol: TCP
       targetPort: 27017
  selector:
    component: runways-db
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-runways-db
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      component: runways-db
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access-runways-db: "1"
        - namespaceSelector:
            matchLabels:
              name: '${NAMESPACE}'
