apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    name: '${NAMESPACE}'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${NAMESPACE}-quota
  namespace: ${NAMESPACE}
spec:
  hard:
    requests.cpu: "1300m"
    requests.memory: 3Gi
    limits.cpu: "1600m"
    limits.memory: 5Gi
